<?php

namespace ApiBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DefaultEntityRepository {

    /*
     * Only admits a single role value
     */
    public function findByRole($criteria, $orderBy, $limit, $offset) {
        
        // Save the role value to filter by
        $roleFilter = $criteria['role'];
        
        // Unset from the general criteria array
        unset($criteria['role']);
        
        // Use regular flow of building the query with all common params
        $qb = $this->getFindByCustomCriteriaQueryBuilder($criteria, $orderBy, $limit, $offset);
        
        // Add the roles 'LIKE' filter, execute the query and return the result
        return $qb->andWhere('x.roles LIKE :role')
                        ->setParameter('role', '%' . $roleFilter . '%')
                        ->getQuery()->getResult();
        
        return $this->createQueryBuilder('u')
                        ->where('u.roles LIKE :role')
                        ->setParameter('role', '%' . $role . '%')
                        ->getQuery()->getResult()
        ;
    }

}
